// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCrawler.Data;

#nullable disable

namespace WebApiCrawler.Migrations
{
    [DbContext(typeof(CrawlerDbContext))]
    [Migration("20240502195238_Migration_v1")]
    partial class Migration_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiCrawler.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WebApiCrawler.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6522cea-bc2c-400f-980a-736296a31c40"),
                            Code = "EK000525407",
                            Name = "Electrolux aparat za kavu",
                            StoreId = new Guid("0a443b7c-cebb-4408-b798-a21be02040c5")
                        },
                        new
                        {
                            Id = new Guid("dd09287a-ef6b-435a-a6b9-a31bab2e041d"),
                            Code = "EK000467594",
                            Name = "TP-Link Deco E4, Mesh Wi-Fi sistem",
                            StoreId = new Guid("0a443b7c-cebb-4408-b798-a21be02040c5")
                        },
                        new
                        {
                            Id = new Guid("da2fe081-a3f9-463b-955b-ecc7aba0b170"),
                            Code = "EK000439180",
                            Name = "Logitech Gaming G435 Lightspeed, bežične slušalice",
                            StoreId = new Guid("0a443b7c-cebb-4408-b798-a21be02040c5")
                        },
                        new
                        {
                            Id = new Guid("05af9724-9298-483a-b4f6-372b351694af"),
                            Code = "EK000586865",
                            Name = "POLAR gradski bicikl",
                            StoreId = new Guid("0a443b7c-cebb-4408-b798-a21be02040c5")
                        },
                        new
                        {
                            Id = new Guid("66dd7d1e-f142-45ac-8a23-7439939b60cd"),
                            Code = "225463979956",
                            Name = "Cambridge Audio R100 FM/AM Stereo Receiver",
                            StoreId = new Guid("cc1de7be-4976-4b30-bf66-fe207218e1c8")
                        },
                        new
                        {
                            Id = new Guid("997c0013-5730-4e0c-a6df-cbd708462bcd"),
                            Code = "155770850364",
                            Name = "Bluetooth Earbuds Headset",
                            StoreId = new Guid("cc1de7be-4976-4b30-bf66-fe207218e1c8")
                        });
                });

            modelBuilder.Entity("WebApiCrawler.Models.WebConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchBox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageFolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlPage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebConfigurations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7829cb16-3ffd-41b6-a2be-f2630c0d15e4"),
                            DisplayType = "WebApiCrawler.AbrakadabraModels.SearchResultAbrakadabraDto",
                            Img = "data-src",
                            ImgTag = "//img[@data-src]",
                            ResultType = "WebApiCrawler.AbrakadabraModels.SearchResultAbrakadabra",
                            SearchBox = "https://www.ekupi.hr/hr/search/autocomplete/SearchBox?term=",
                            StorageExtension = ".jpg",
                            StorageFolder = "ImagesDatabase",
                            StoreId = new Guid("0a443b7c-cebb-4408-b798-a21be02040c5"),
                            UrlPage = "https://www.ekupi.hr/p/"
                        },
                        new
                        {
                            Id = new Guid("7aa3d795-1db9-4e2c-8979-4908e69c3eaf"),
                            DisplayType = "WebApiCrawler.AbrakadabraModels.SearchResultAbrakadabraDto",
                            Img = "src",
                            ImgTag = "//img[@data-zoom-image]/@data-zoom-image",
                            ResultType = "WebApiCrawler.AbrakadabraModels.SearchResultAbrakadabra",
                            SearchBox = "https://www.abrakadabra.com/hr-HR/search/autocomplete/SearchBox?term=",
                            StorageExtension = ".png",
                            StorageFolder = "ImagesDatabase",
                            StoreId = new Guid("eeb699b6-56e8-48ff-829d-416876d4b2de"),
                            UrlPage = "https://www.abrakadabra.com/p/"
                        },
                        new
                        {
                            Id = new Guid("b8bf6a33-538d-4354-9d95-bf75b33fd155"),
                            DisplayType = "",
                            Img = "data-src",
                            ImgTag = "//img[@data-src]",
                            ResultType = "",
                            SearchBox = "",
                            StorageExtension = ".jpeg",
                            StorageFolder = "ImagesDatabase",
                            StoreId = new Guid("cc1de7be-4976-4b30-bf66-fe207218e1c8"),
                            UrlPage = "https://www.ebay.com/itm/"
                        },
                        new
                        {
                            Id = new Guid("d74c97ac-5e43-4cfa-9f4a-9c8c585d523c"),
                            DisplayType = "WebApiCrawler.ModelsHGSpot.SearchResultHgSpotDto",
                            Img = "src",
                            ImgTag = "//div[@id=\"product-gallery\"]//img",
                            ResultType = "WebApiCrawler.ModelsHGSpot.SearchResultHgSpot",
                            SearchBox = "https://www.hgspot.hr/api/search-final.php?keyword=",
                            StorageExtension = ".jpeg",
                            StorageFolder = "ImagesDatabase",
                            StoreId = new Guid("f04233eb-4d2e-4c53-a5b0-9a76b5ef582f"),
                            UrlPage = "https://www.hgspot.hr/"
                        },
                        new
                        {
                            Id = new Guid("e8f377ef-7816-4fb9-9874-af11a5897934"),
                            DisplayType = "WebApiCrawler.Models.ModelsMikronis.SearchResultMikronisDto",
                            Img = "src",
                            ImgTag = "//div[@class=\"product-pic-inner\"]//img",
                            ResultType = "WebApiCrawler.Models.ModelsMikronis.SearchResultMikronis",
                            SearchBox = "https://www.mikronis.hr/api/shopapi/getSearchSuggestion?search=",
                            StorageExtension = ".jpeg",
                            StorageFolder = "ImagesDatabase",
                            StoreId = new Guid("dfdcc0f0-6ab2-4b77-8560-2112d5dd4190"),
                            UrlPage = "https://www.mikronis.hr/Proizvod/"
                        },
                        new
                        {
                            Id = new Guid("331d9f95-55b9-4738-a020-46781374aed7"),
                            DisplayType = "WebApiCrawler.Models.ModelsInstarInformatika.SearchResultInstarInformatikaDto",
                            Img = "src",
                            ImgTag = "//a[@class=\"fancybox\"]/img",
                            ResultType = "WebApiCrawler.Models.ModelsInstarInformatika.SearchResultInstarInformatika",
                            SearchBox = "https://www.instar-informatika.hr/api/search/multi/?term=",
                            StorageExtension = ".jpg",
                            StorageFolder = "ImagesDatabase",
                            StoreId = new Guid("85f0ae0e-32c4-4110-9752-bafa7e781be1"),
                            UrlPage = "https://www.instar-informatika.hr/"
                        });
                });

            modelBuilder.Entity("WebApiCrawler.Models.WebStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebStores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a443b7c-cebb-4408-b798-a21be02040c5"),
                            Name = "eKupi"
                        },
                        new
                        {
                            Id = new Guid("eeb699b6-56e8-48ff-829d-416876d4b2de"),
                            Name = "Abrakadabra"
                        },
                        new
                        {
                            Id = new Guid("cc1de7be-4976-4b30-bf66-fe207218e1c8"),
                            Name = "eBay"
                        },
                        new
                        {
                            Id = new Guid("f04233eb-4d2e-4c53-a5b0-9a76b5ef582f"),
                            Name = "HG Spot"
                        },
                        new
                        {
                            Id = new Guid("dfdcc0f0-6ab2-4b77-8560-2112d5dd4190"),
                            Name = "Mikronis"
                        },
                        new
                        {
                            Id = new Guid("85f0ae0e-32c4-4110-9752-bafa7e781be1"),
                            Name = "Instar informatika"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
