using WebApiCrawler.Models.ModelsMikronis;

namespace WebApiCrawler.Models.ModelsMikronis
{
    public class ProductMicronis
    {
        public bool isFavorite { get; set; }
        public int ElasticBoost { get; set; }
        public double Savings_percentage { get; set; }
        public string CJI_GetMainGroup { get; set; }
        public string CJI_ident { get; set; }
        public string GenerateUrl { get; set; }
        public int Id { get; set; }
        public int OldId { get; set; }
        public string Code { get; set; }
        public int ProductGroupId { get; set; }
        public int SuperProductGroupId { get; set; }
        public int ChildrenCount { get; set; }
        public List<Related> Related { get; set; }
        public List<object> RelatedGroups { get; set; }
        public List<object> RelatedManufacturers { get; set; }
        public string UrlName { get; set; }
        public string GenerateReadableUrl { get; set; }
        public string GenerateAbsoluteUrl { get; set; }
        public string GenerateCatalogueUrl { get; set; }
        public List<File> Files { get; set; }
        public int ManufacturerId { get; set; }
        public Manufacturers Manufacturers { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerUrlName { get; set; }
        public string Name { get; set; }
        public List<string> Name_EL { get; set; }
        public string shopName { get; set; }
        public double Vpc { get; set; }
        public double Mpc { get; set; }
        public double FinalPriceToPay { get; set; }
        public double FinalPriceToPayWithVAT { get; set; }
        public double FinalPriceToPayWithoutVAT { get; set; }
        public string FinalPriceToPay_print { get; set; }
        public string FinalPriceToPayWithVAT_print { get; set; }
        public string Mpc_print { get; set; }
        public double SinglePriceToPay { get; set; }
        public string SinglePriceToPay_print { get; set; }
        public double LowestMonthlyMpc { get; set; }
        public double LowestMonthlyVpc { get; set; }
        public string LowestMonthlyMpc_print { get; set; }
        public string LowestMonthlyVpc_print { get; set; }
        public double SinglePriceToPayVPC { get; set; }
        public string SinglePriceToPayVPC_print { get; set; }
        public double MpcCards { get; set; }
        public string MpcCards_print { get; set; }
        public double Savings { get; set; }
        public string Savings_print { get; set; }
        public string Savings_percentage_print { get; set; }
        public string Vpc_print { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public int Sort { get; set; }
        public DateTime LastUpdate { get; set; }
        public bool Enabled { get; set; }
        public bool Published { get; set; }
        public int Stock { get; set; }
        public double MinQuantity { get; set; }
        public double PurchaseInterval { get; set; }
        public double SupplierStock { get; set; }
        public int B2BStock { get; set; }
        public int StockSum { get; set; }
        public bool IsNew { get; set; }
        public bool IsSpecial { get; set; }
        public double Size { get; set; }
        public double Weight { get; set; }
        public bool IsDelivery { get; set; }
        public bool IsVoucher { get; set; }
        public bool IsCopy { get; set; }
        public double Mpc_original { get; set; }
        public bool IsPackaging { get; set; }
        public int ParentProductId { get; set; }
        public int ParentId { get; set; }
        public int foreign_id { get; set; }
        public List<Attribute> Attributes { get; set; }
        public List<VariantAttribute> Variant_Attributes { get; set; }
        public List<Group> groups { get; set; }
        public double Quantity { get; set; }
        public List<object> childProductIds { get; set; }
        public List<object> childProductCodes { get; set; }
        public List<int> relatedProductIds { get; set; }
        public List<object> modifiers { get; set; }
        public bool isBought { get; set; }
        public bool isInWishlist { get; set; }
        public double BasePrice { get; set; }
        public double BaseVpc { get; set; }
        public string BasePrice_print { get; set; }
        public string BaseVpc_print { get; set; }
        public List<Variant> Variants { get; set; }
        public GroupAggregations groupAggregations { get; set; }
        public AttributeAggregations attributeAggregations { get; set; }
        public List<Discount> Discounts { get; set; }
        public List<UsedDiscount> UsedDiscounts { get; set; }
        public int VAT_id { get; set; }
        public VAT VAT { get; set; }
        public double VATAmount { get; set; }
        public string VATAmount_print { get; set; }
        public bool showChildren { get; set; }
        public bool rootVariant { get; set; }
        public double VariantMinPrice { get; set; }
        public string VariantMinPrice_print { get; set; }
        public double VariantMaxPrice { get; set; }
        public string VariantMaxPrice_print { get; set; }
        public int SeriesId { get; set; }
        public string MainImageUrl { get; set; }
        public string MainImage { get; set; }
        public double AverageScore { get; set; }
        public int NumberOfReviews { get; set; }
        public List<object> Errors { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }
        public string SKU { get; set; }
        public string Barcode { get; set; }
        public int WebShopId { get; set; }
        public List<object> SortProductsInGroup { get; set; }
        public string Secondary_FinalPriceToPay_print { get; set; }
        public string Secondary_FinalPriceToPayWithVAT_print { get; set; }
        public string Secondary_SinglePriceToPay_print { get; set; }
        public Translations Translations { get; set; }
        public string Description2 { get; set; }
    }
}
